server:
  port: 9080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml

logging:
  level:
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG
# swagger配置
swagger:
  title: 'SuperSonic平台接口文档'
  base:
    package: com.tencent.supersonic
  description: 'SuperSonic平台接口文档'
  url: ''
  contact:
    name:
    email:
    url: ''
  version: 3.0